
import { Store, Translation } from './types';

export const STORES: Store[] = [
  { id: 'amazon-sa', name: 'Amazon SA', nameAr: 'أمازون السعودية', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Amazon_icon.svg', url: 'https://www.amazon.sa/', description: 'World of Amazon', descriptionAr: 'عالم أمازون بين يديك' },
  { id: 'shein', name: 'SHEIN', nameAr: 'شي إن', logo: 'https://cdn.worldvectorlogo.com/logos/shein-1.svg', url: 'https://ar.shein.com/', description: 'Latest Fashion', descriptionAr: 'أحدث صيحات الموضة' },
  { id: 'noon', name: 'NOON', nameAr: 'نون', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Noon_logo.svg', url: 'https://www.noon.com/', description: 'Everything here', descriptionAr: 'كل ما تحتاجه في مكان واحد' },
  { id: 'aliexpress', name: 'AliExpress', nameAr: 'علي إكسبريس', logo: 'https://cdn.worldvectorlogo.com/logos/aliexpress-1.svg', url: 'https://www.aliexpress.com/', description: 'Global deals', descriptionAr: 'صفقات عالمية مذهلة' },
  { id: 'trendyol', name: 'Trendyol', nameAr: 'ترينديول', logo: 'https://cdn.worldvectorlogo.com/logos/trendyol.svg', url: 'https://www.trendyol.com/', description: 'Turkish Quality', descriptionAr: 'الجودة والأناقة التركية' },
  { id: 'niceone', name: 'Nice One', nameAr: 'نايس ون', logo: 'https://niceonesa.com/favicon.ico', url: 'https://niceonesa.com/', description: 'Beauty products', descriptionAr: 'منتجات التجميل والعناية' },
  { id: 'assaf', name: 'Assaf Store', nameAr: 'عساف للعطور', logo: 'https://assaf.store/favicon.ico', url: 'https://assaf.store/', description: 'Premium Perfumes', descriptionAr: 'عطور عساف الفاخرة' },
  { id: 'laverne', name: 'Laverne', nameAr: 'لافيرن', logo: 'https://laverne.com.sa/favicon.ico', url: 'https://laverne.com.sa/', description: 'Luxury Scents', descriptionAr: 'أرقى عطور لافيرن' },
  { id: 'dakhon', name: 'Dakhon', nameAr: 'دخون الإماراتية', logo: 'https://dakhon.com/favicon.ico', url: 'https://dakhon.com/', description: 'Emirati Oud', descriptionAr: 'البخور والعطور الإماراتية' },
  { id: 'alezz', name: 'Al-Ezz Oud', nameAr: 'العز للعود', logo: 'https://alezzoud.com/favicon.ico', url: 'https://alezzoud.com/', description: 'Authentic Oud', descriptionAr: 'أفخم أنواع العود' },
  { id: '6thstreet', name: '6thStreet', nameAr: '6 ستريت', logo: 'https://www.6thstreet.com/static/version1706173044/frontend/6thStreet/6thstreet/en_US/images/logo.svg', url: 'https://www.6thstreet.com/', description: 'Top Brands', descriptionAr: 'أرقى الماركات العالمية' },
  { id: 'iherb', name: 'iHerb', nameAr: 'إيهيرب', logo: 'https://cdn.worldvectorlogo.com/logos/iherb.svg', url: 'https://www.iherb.com/', description: 'Natural Health', descriptionAr: 'المكملات والعناية الصحية' },
  { id: 'salla', name: 'Salla', nameAr: 'منصة سلة', logo: 'https://salla.sa/assets/images/logo-light.svg', url: 'https://salla.sa/', description: 'Saudi Stores', descriptionAr: 'المتاجر السعودية المحلية' },
  { id: 'fordeal', name: 'Fordeal', nameAr: 'فورديل', logo: 'https://cdn.worldvectorlogo.com/logos/fordeal.svg', url: 'https://www.fordeal.com/', description: 'Global Shopping', descriptionAr: 'تسوق عالمي شامل' },
];

export const APP_LOGO = "data:image/svg+xml,%3Csvg width='500' height='500' viewBox='0 0 500 500' xmlns='http://www.w3.org/2000/svg'%3E%3Cdefs%3E%3ClinearGradient id='goldGradient' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' style='stop-color:%23d4af37;stop-opacity:1' /%3E%3Cstop offset='50%25' style='stop-color:%23f9f295;stop-opacity:1' /%3E%3Cstop offset='100%25' style='stop-color:%23b8860b;stop-opacity:1' /%3E%3C/linearGradient%3E%3C/defs%3E%3Cpath d='M250 50 L423.2 150 L423.2 350 L250 450 L76.8 350 L76.8 150 Z' fill='none' stroke='url(%23goldGradient)' stroke-width='40' /%3E%3Cpath d='M200 200 L300 200 L300 300 L200 300 Z' fill='url(%23goldGradient)' /%3E%3Ctext x='50%25' y='55%25' dominant-baseline='middle' text-anchor='middle' font-family='Arial, sans-serif' font-size='180' font-weight='bold' fill='url(%23goldGradient)'%3EC%3C/text%3E%3C/svg%3E";
// Note: To use your custom logo, upload it as 'logo.png' to the root directory and change APP_LOGO back to "./logo.png"

export const SOCIAL_LINKS = {
  instagram: 'https://www.instagram.com/collection.yem?igsh=MXNla2JmMHI2MWdobQ==',
  facebook: 'https://www.facebook.com/collection.yemen.store?mibextid=wwXIfr&mibextid=wwXIfr',
  whatsapp: 'https://wa.me/967774757728',
  telegram: 'https://t.me/collection_yemen',
  x: 'https://x.com/collection_yemen'
};

export const BRIDE_CATEGORIES = [
  { id: 'dresses', name: 'Wedding Dresses', nameAr: 'فساتين زفاف' },
  { id: 'hairdresser', name: 'Hairdresser', nameAr: 'كوافير' },
  { id: 'cosmetics', name: 'Cosmetics', nameAr: 'أدوات تجميل' },
];

export const FLASH_SALE_END_TIME = "2026-03-15T00:00:00Z";

export const TRANSLATIONS: Translation = {
  welcome: { en: 'Collection', ar: 'كوليكشن' },
  aboutUs: { en: 'About Us', ar: 'من نحن' },
  aboutUsDesc: { en: 'Collection is your premier logistics partner in Yemen, bridging the gap between global markets and local convenience. We specialize in international purchasing and secure delivery.', ar: 'كوليكشن هي شريكك اللوجستي الأول في اليمن، حيث نربط بين الأسواق العالمية والراحة المحلية. نحن متخصصون في الشراء الدولي والتوصيل الآمن.' },
  brideServices: { en: 'Bride Services', ar: 'خدمات العروسة' },
  brideServicesSubtitle: { en: 'Everything you need for your perfect day', ar: 'كل ما تحتاجينه ليومك المثالي' },
  happyCustomersCount: { en: '2,000+ happy customers', ar: 'أكثر من 2000 عميلة سعيدة' },
  weddingDresses: { en: 'Wedding Dresses', ar: 'فساتين زفاف' },
  accessories: { en: 'Accessories', ar: 'إكسسوارات' },
  makeupArtists: { en: 'Makeup Artists', ar: 'خبيرات تجميل' },
  photography: { en: 'Photography', ar: 'تصوير فوتوغرافي' },
  bridalBouquets: { en: 'Bridal Bouquets', ar: 'مسكات عرائس' },
  weddingPlanning: { en: 'Wedding Planning', ar: 'تنظيم حفلات' },
  invitationsGifts: { en: 'Invitations & Gifts', ar: 'دعوات وهدايا' },
  fromPrice: { en: 'From SAR', ar: 'ابتداءً من' },
  bookNow: { en: 'Book Now', ar: 'احجزي الآن' },
  premiumExperience: { en: 'Premium Shopping Experience', ar: 'تجربة تسوق فاخرة' },
  discoverPremium: { en: 'Discover Premium', ar: 'اكتشف الفخامة' },
  heroSubtitle: { en: 'Your gateway to luxury products, global shopping, and exclusive bridal services — all in one destination.', ar: 'بوابتك للمنتجات الفاخرة، التسوق العالمي، وخدمات العروسة الحصرية — كل ذلك في وجهة واحدة.' },
  exploreNow: { en: 'Explore Now', ar: 'استكشف الآن' },
  countries: { en: 'Countries', ar: 'دولة' },
  ordersDelivered: { en: 'Orders Delivered', ar: 'طلب تم تسليمه' },
  products: { en: 'Products', ar: 'منتج' },
  flashSale: { en: 'Flash Sale', ar: 'عروض خاطفة' },
  flashSaleSubtitle: { en: 'Limited time offers — grab them before they\'re gone!', ar: 'عروض لفترة محدودة — سارع بالحصول عليها قبل نفاذ الكمية!' },
  saleEndsIn: { en: 'Sale ends in', ar: 'ينتهي العرض خلال' },
  hours: { en: 'Hours', ar: 'ساعة' },
  minutes: { en: 'Minutes', ar: 'دقيقة' },
  seconds: { en: 'Seconds', ar: 'ثانية' },
  shopAnywhere: { en: 'By one click, order arrives to your door', ar: 'بضغطة زر يوصل طلبك من العالم لباب بيتك' },
  heroDesc: { en: 'Comprehensive logistics. Shop global • Pay local • Track easy', ar: 'خدمات لوجستية شاملة وموحدة لليمن. تسوّق عالميا • ادفع محليًا • وتتبع طلبك بكل سهولة' },
  logisticsYemen: { en: 'Unified Logistics Services in Yemen', ar: 'خدمات لوجستية موحدة في اليمن' },
  howToOrder: { en: 'How to Buy?', ar: 'كيفية الشراء؟' },
  hotDeals: { en: 'Flash Offers', ar: 'عروض حصرية' },
  specialOffers: { en: 'Special Price', ar: 'سعر خاص' },
  step1Title: { en: 'Pick Store & Item', ar: 'اختر المتجر والمنتج' },
  step1Desc: { en: 'Browse your favorite global store and copy the product link.', ar: 'تصفح متجرك العالمي المفضل وانسخ رابط المنتج الذي تريده.' },
  step2Title: { en: 'Review & Pricing', ar: 'المراجعة والتسعير' },
  step2Desc: { en: 'We will review your link and set the final price for you.', ar: 'سنقوم بمراجعة الرابط وتحديد السعر النهائي لك.' },
  step3Title: { en: 'Local Payment', ar: 'دفع محلي آمن' },
  step3Desc: { en: 'Confirm and pay via Kuraimi, OneCash or Jeeb Wallet.', ar: 'أكد طلبك وادفع عبر الكريمي، ون كاش، أو محفظة جيب.' },
  step4Title: { en: 'Track Order', ar: 'تتبع طلبك حتى وصولها' },
  step4Desc: { en: 'Track your package from warehouses to your door in Yemen.', ar: 'تابع شحنتك من المخازن العالمية حتى وصولها لباب بيتك في اليمن.' },
  login: { en: 'Login', ar: 'دخول' },
  signup: { en: 'Sign Up', ar: 'إنشاء حساب' },
  logout: { en: 'Logout', ar: 'خروج' },
  cart: { en: 'My Cart', ar: 'سلتي' },
  checkout: { en: 'Checkout', ar: 'الدفع' },
  total: { en: 'Total', ar: 'المجموع' },
  emptyCart: { en: 'Your cart is empty', ar: 'سلتك فارغة' },
  trackOrder: { en: 'Track Order', ar: 'تتبع طلبك' },
  officialStore: { en: 'Official Site', ar: 'الموقع الرسمي' },
  localStore: { en: 'Collection Store', ar: 'متجر كوليكشن' },
  googleLogin: { en: 'Login with Google', ar: 'الدخول بحساب جوجل' },
  whatsappSupport: { en: 'WhatsApp Support', ar: 'الدعم الفني' },
  restricted: { en: 'Please login first', ar: 'يرجى تسجيل الدخول أولاً' },
  addToCart: { en: 'Add to Cart', ar: 'إضافة للسلة' },
  selectSize: { en: 'Select Size', ar: 'اختر المقاس' },
  selectColor: { en: 'Select Color', ar: 'اختر اللون' },
  allProducts: { en: 'All Items', ar: 'جميع المنتجات' },
  orderSuccess: { en: 'Order Successful', ar: 'تم الطلب بنجاح' },
  orderNumber: { en: 'Order Number', ar: 'رقم الطلب' },
  copied: { en: 'Copied!', ar: 'تم النسخ!' },
  copyId: { en: 'Copy ID', ar: 'نسخ الرقم' },
  visaMada: { en: 'Visa / Mada', ar: 'فيزا / مدى' },
  localYemen: { en: 'Local Payment', ar: 'دفع محلي' },
  kuraimi: { en: 'Kuraimi Bank', ar: 'بنك الكريمي' },
  jeeb: { en: 'Jeeb Wallet', ar: 'محفظة جيب' },
  onecash: { en: 'One Cash', ar: 'ون كاش' },
  track: { en: 'Track', ar: 'تتبع' },
  orderNotFound: { en: 'Order not found', ar: 'الطلب غير موجود' },
  adminDashboard: { en: 'Dashboard', ar: 'لوحة التحكم' },
  manageOrders: { en: 'Manage Orders', ar: 'إدارة الطلبات' },
  status_pending: { en: 'Reviewing', ar: 'قيد المراجعة' },
  status_purchased: { en: 'Purchased', ar: 'تم الشراء' },
  status_shipped: { en: 'Shipped', ar: 'تم الشحن' },
  status_yemen: { en: 'In Yemen', ar: 'وصل اليمن' },
  status_delivery: { en: 'Delivering', ar: 'قيد التوصيل' },
  status_completed: { en: 'Delivered', ar: 'تم التسليم' },
  status_cancelled: { en: 'Cancelled', ar: 'ملغي' },
  status_awaiting_quote: { en: 'Awaiting Quote', ar: 'بانتظار التسعير' },
  status_quote_ready: { en: 'Quote Ready - Please Pay', ar: 'تم التسعير - يرجى الدفع' },
  requestQuote: { en: 'Request Quote', ar: 'طلب تسعير' },
  howToShopToday: { en: 'How would you like to shop today?', ar: 'كيف تحب أن تتسوق اليوم؟' },
  internationalShopping: { en: 'International Shopping', ar: 'التسوق من المواقع العالمية' },
  fromWorldToDoor: { en: 'From the world to your door', ar: 'من العالم إلى باب بيتك' },
  internationalDesc: { en: 'We order for you from any global store and deliver to Yemen with local payment and full tracking.', ar: 'نطلب لك من أي متجر عالمي ونوصله إلى اليمن مع دفع محلي وتتبع كامل.' },
  orderFromAbroad: { en: 'Order from abroad', ar: 'اطلب من الخارج' },
  readyForDelivery: { en: 'Ready for Delivery', ar: 'منتجات جاهزة للتسليم' },
  wantSomethingFast: { en: 'Want something fast?', ar: 'تبي شي يوصل بسرعة؟' },
  readyDesc: { en: 'Brand perfumes ready for immediate delivery within Yemen.', ar: 'عطور ماركات جاهزة للتسليم الفوري داخل اليمن.' },
  shopNow: { en: 'Shop Now', ar: 'تسوق الآن' },
  brideSection: { en: 'Bride Section', ar: 'قسم العروسة' },
  readyForNewStage: { en: 'Ready for a new stage?', ar: 'جاهزة لمرحلة جديدة؟' },
  brideDesc: { en: 'All the bride\'s needs in one place - complete organization and ease of choice.', ar: 'كل احتياجات العروسة في مكان واحد – تنظيم كامل وسهولة اختيار.' },
  startPreparing: { en: 'Start Preparing', ar: 'ابدأ التجهيز' },
  howServiceWorks: { en: 'How the service works', ar: 'كيف تعمل الخدمة' },
  step1: { en: 'Send product link', ar: 'أرسل رابط المنتج' },
  step2: { en: 'We buy and ship', ar: 'نقوم بالشراء والشحن' },
  step3: { en: 'Receive and pay locally', ar: 'تستلم وتدفع محليًا' },
  whyOrderWithUs: { en: 'Why order with us?', ar: 'ليش تطلب معنا؟' },
  localPaymentOnDelivery: { en: 'Local payment on delivery', ar: 'دفع محلي عند الاستلام' },
  fullTracking: { en: 'Full order tracking', ar: 'تتبع كامل للطلب' },
  directWhatsappSupport: { en: 'Direct WhatsApp support', ar: 'دعم مباشر عبر واتساب' },
  fastCustomerService: { en: 'Fast customer service', ar: 'خدمة عملاء سريعة' },
  easyReturn: { en: 'Return if there\'s a problem', ar: 'استرجاع في حال وجود مشكلة' },
  noBankCardNeeded: { en: 'No bank card needed - Cash on delivery', ar: 'لا تحتاج بطاقة بنكية – الدفع عند الاستلام' },
  siteIdentity: { en: 'Logistics services company and purchasing intermediary from global stores within Yemen.', ar: 'شركة خدمات لوجستية ووسيط شراء من المتاجر العالمية داخل اليمن.' },
  customerReviews: { en: 'Customer Reviews', ar: 'تقييمات العملاء' },
  addReview: { en: 'Add your review', ar: 'أضف تقييمك' },
  completedOrders: { en: 'Completed Orders', ar: 'الطلبات المنجزة' },
  happyCustomers: { en: 'Happy Customers', ar: 'عملاء سعداء' },
  offers: { en: 'Offers', ar: 'العروض' },
  viewAll: { en: 'View All', ar: 'عرض الكل' },
};
